#!/bin/sh

`yarn build:clean`
build=$?

if [ $build = 1 ]; then
  echo "::: BUILD SUCCESS :::"
  echo "::: EXIT CODE :::" ${build}
  `git add .`
else
  echo "::: BUILD ERROR :::"
  echo "::: EXIT CODE :::" ${build}
  exit 1
fi

`yarn test`
test=$?

if [ $test = 1 ]; then
  echo "::: ALL TEST PASS :::"
else
  echo "::: TEST FAIL :::"
  echo "::: This change will not be committed..."
  exit 1
fi

exit 0
