"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.yPowerApproximation = exports.xPowerApproximation = exports.surfaceAreaOfSphere = exports.inCircle = exports.constant = exports.distanceLineToPoint = exports.distanceOnSphere = exports.distance3d = exports.distance = exports.kelvinToRoemer = exports.kelvinToReaumur = exports.kelvinToRankine = exports.kelvinToNewton = exports.kelvinToDelisle = exports.kelvinToFahrenheit = exports.kelvinToCelsius = exports.fahrenheitToKelvin = exports.fahrenheitToCelsius = exports.celsiusToKelvin = exports.celsiusToFahrenheit = exports.degreeToRadian = exports.lcm = exports.gcd = exports.factorial = exports.median = exports.sum = exports.average = exports.weightedAverage = exports.repeatedCombine = exports.repeatedPerm = exports.combine = exports.perm = exports.aspectRatio = void 0;
var aspect_ratio_1 = require("./aspect-ratio");
Object.defineProperty(exports, "aspectRatio", { enumerable: true, get: function () { return aspect_ratio_1.aspectRatio; } });
var combination_1 = require("./combination");
Object.defineProperty(exports, "perm", { enumerable: true, get: function () { return combination_1.perm; } });
Object.defineProperty(exports, "combine", { enumerable: true, get: function () { return combination_1.combine; } });
Object.defineProperty(exports, "repeatedPerm", { enumerable: true, get: function () { return combination_1.repeatedPerm; } });
Object.defineProperty(exports, "repeatedCombine", { enumerable: true, get: function () { return combination_1.repeatedCombine; } });
var weighted_average_1 = require("./weighted-average");
Object.defineProperty(exports, "weightedAverage", { enumerable: true, get: function () { return weighted_average_1.weightedAverage; } });
var average_1 = require("./average");
Object.defineProperty(exports, "average", { enumerable: true, get: function () { return average_1.average; } });
var sum_1 = require("./sum");
Object.defineProperty(exports, "sum", { enumerable: true, get: function () { return sum_1.sum; } });
var median_1 = require("./median");
Object.defineProperty(exports, "median", { enumerable: true, get: function () { return median_1.median; } });
var factorial_1 = require("./factorial");
Object.defineProperty(exports, "factorial", { enumerable: true, get: function () { return factorial_1.factorial; } });
var gcd_1 = require("./gcd");
Object.defineProperty(exports, "gcd", { enumerable: true, get: function () { return gcd_1.gcd; } });
var lcm_1 = require("./lcm");
Object.defineProperty(exports, "lcm", { enumerable: true, get: function () { return lcm_1.lcm; } });
var convert_1 = require("./convert");
Object.defineProperty(exports, "degreeToRadian", { enumerable: true, get: function () { return convert_1.degreeToRadian; } });
var convert_2 = require("./convert");
Object.defineProperty(exports, "celsiusToFahrenheit", { enumerable: true, get: function () { return convert_2.celsiusToFahrenheit; } });
Object.defineProperty(exports, "celsiusToKelvin", { enumerable: true, get: function () { return convert_2.celsiusToKelvin; } });
Object.defineProperty(exports, "fahrenheitToCelsius", { enumerable: true, get: function () { return convert_2.fahrenheitToCelsius; } });
Object.defineProperty(exports, "fahrenheitToKelvin", { enumerable: true, get: function () { return convert_2.fahrenheitToKelvin; } });
var convert_3 = require("./convert");
Object.defineProperty(exports, "kelvinToCelsius", { enumerable: true, get: function () { return convert_3.kelvinToCelsius; } });
Object.defineProperty(exports, "kelvinToFahrenheit", { enumerable: true, get: function () { return convert_3.kelvinToFahrenheit; } });
Object.defineProperty(exports, "kelvinToDelisle", { enumerable: true, get: function () { return convert_3.kelvinToDelisle; } });
Object.defineProperty(exports, "kelvinToNewton", { enumerable: true, get: function () { return convert_3.kelvinToNewton; } });
var convert_4 = require("./convert");
Object.defineProperty(exports, "kelvinToRankine", { enumerable: true, get: function () { return convert_4.kelvinToRankine; } });
Object.defineProperty(exports, "kelvinToReaumur", { enumerable: true, get: function () { return convert_4.kelvinToReaumur; } });
Object.defineProperty(exports, "kelvinToRoemer", { enumerable: true, get: function () { return convert_4.kelvinToRoemer; } });
var distance_1 = require("./distance");
Object.defineProperty(exports, "distance", { enumerable: true, get: function () { return distance_1.distance; } });
Object.defineProperty(exports, "distance3d", { enumerable: true, get: function () { return distance_1.distance3d; } });
Object.defineProperty(exports, "distanceOnSphere", { enumerable: true, get: function () { return distance_1.distanceOnSphere; } });
Object.defineProperty(exports, "distanceLineToPoint", { enumerable: true, get: function () { return distance_1.distanceLineToPoint; } });
var distance_2 = require("./distance");
Object.defineProperty(exports, "constant", { enumerable: true, get: function () { return distance_2.constant; } });
Object.defineProperty(exports, "inCircle", { enumerable: true, get: function () { return distance_2.inCircle; } });
var equations_1 = require("./equations");
Object.defineProperty(exports, "surfaceAreaOfSphere", { enumerable: true, get: function () { return equations_1.surfaceAreaOfSphere; } });
var fomulas_1 = require("./fomulas");
Object.defineProperty(exports, "xPowerApproximation", { enumerable: true, get: function () { return fomulas_1.xPowerApproximation; } });
Object.defineProperty(exports, "yPowerApproximation", { enumerable: true, get: function () { return fomulas_1.yPowerApproximation; } });
