"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.kelvinToRoemer = exports.kelvinToReaumur = exports.kelvinToRankine = exports.kelvinToNewton = exports.kelvinToDelisle = exports.kelvinToFahrenheit = exports.kelvinToCelsius = exports.fahrenheitToKelvin = exports.fahrenheitToCelsius = exports.celsiusToKelvin = exports.celsiusToFahrenheit = exports.radianToDegree = exports.degreeToRadian = void 0;
var angle_1 = require("./angle");
Object.defineProperty(exports, "degreeToRadian", { enumerable: true, get: function () { return angle_1.degreeToRadian; } });
Object.defineProperty(exports, "radianToDegree", { enumerable: true, get: function () { return angle_1.radianToDegree; } });
var temperatures_1 = require("./temperatures");
Object.defineProperty(exports, "celsiusToFahrenheit", { enumerable: true, get: function () { return temperatures_1.celsiusToFahrenheit; } });
Object.defineProperty(exports, "celsiusToKelvin", { enumerable: true, get: function () { return temperatures_1.celsiusToKelvin; } });
Object.defineProperty(exports, "fahrenheitToCelsius", { enumerable: true, get: function () { return temperatures_1.fahrenheitToCelsius; } });
Object.defineProperty(exports, "fahrenheitToKelvin", { enumerable: true, get: function () { return temperatures_1.fahrenheitToKelvin; } });
var temperatures_2 = require("./temperatures");
Object.defineProperty(exports, "kelvinToCelsius", { enumerable: true, get: function () { return temperatures_2.kelvinToCelsius; } });
Object.defineProperty(exports, "kelvinToFahrenheit", { enumerable: true, get: function () { return temperatures_2.kelvinToFahrenheit; } });
Object.defineProperty(exports, "kelvinToDelisle", { enumerable: true, get: function () { return temperatures_2.kelvinToDelisle; } });
Object.defineProperty(exports, "kelvinToNewton", { enumerable: true, get: function () { return temperatures_2.kelvinToNewton; } });
var temperatures_3 = require("./temperatures");
Object.defineProperty(exports, "kelvinToRankine", { enumerable: true, get: function () { return temperatures_3.kelvinToRankine; } });
Object.defineProperty(exports, "kelvinToReaumur", { enumerable: true, get: function () { return temperatures_3.kelvinToReaumur; } });
Object.defineProperty(exports, "kelvinToRoemer", { enumerable: true, get: function () { return temperatures_3.kelvinToRoemer; } });
