name: Codecov Coverage
on: [push]
jobs:
  build-push-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '15.11.0'
      - name: Auto test
        run: |
          yarn install
          yarn test
      - name: Test result branch
        if: success()
        shell: bash
